#!/usr/bin/env python
"""
Does the full weak set give us extra REAL failure examples beyond gold?

Diagnostic only — reads data/raw/*.parquet, writes reports/weak_failure_pool.md.
Touches no pipeline or model code.

Context: label_vs_population.md established that weak labels are trustworthy
(TERMINATED/WITHDRAWN trials are ~99% agreed as failures by both weak and gold).
So a non-completed weak trial is effectively a real failure example. The question
for Phase 2 training strategy: is the full weak set a large pool of ADDITIONAL
failure examples beyond gold, or is it so completion-dominated that gold is the
only source of failures?
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).parents[1]
RAW = ROOT / "data" / "raw"
OUT_MD = ROOT / "reports" / "weak_failure_pool.md"

PHASE_NAMES = {1: "Phase I", 2: "Phase II", 3: "Phase III"}


def _bucket(s: str) -> str:
    s = str(s).upper()
    return s if s in ("COMPLETED", "TERMINATED", "WITHDRAWN") else "OTHER"


def _pct(v: float) -> str:
    return f"{v:.1%}"


def main() -> None:
    gold = pd.read_parquet(RAW / "cto_gold.parquet")
    gold_ids = set(gold["nct_id"])
    gold_y = dict(zip(gold["nct_id"], gold["y"], strict=True))
    studies = pd.read_parquet(
        RAW / "aact_studies_snapshot.parquet", columns=["nct_id", "overall_status"]
    )

    md: list[str] = []
    md.append("# Weak-Set Failure Pool")
    md.append("")
    md.append("Generated by `python scripts/weak_failure_pool.py`. Diagnostic only.")
    md.append("")
    md.append(
        "Non-completed = TERMINATED + WITHDRAWN. Per `label_vs_population.md` these are "
        "~99% agreed as failures by both weak and gold labels, so they count as real "
        'failure examples. "New" = weak trials whose nct_id is not already in the gold set.'
    )
    md.append("")

    summary_rows = []
    print(
        f"{'Phase':>10} | {'non-compl':>9} | {'new fail':>8} | {'gold fail':>9} | "
        f"{'new/gold':>8} | {'new success':>11}"
    )
    print("-" * 72)

    for p in (1, 2, 3):
        weak = pd.read_parquet(RAW / f"cto_phase{p}.parquet")
        m = weak.merge(studies, on="nct_id", how="left")
        m["bucket"] = m["overall_status"].map(_bucket)

        n = len(m)
        counts = m["bucket"].value_counts()

        # Part 1 — status breakdown
        md.append(f"## {PHASE_NAMES[p]}  (weak n = {n:,})")
        md.append("")
        md.append("| overall_status | n | % |")
        md.append("|----------------|---|---|")
        for status in ("COMPLETED", "TERMINATED", "WITHDRAWN", "OTHER"):
            c = int(counts.get(status, 0))
            md.append(f"| {status} | {c:,} | {_pct(c / n)} |")

        # Part 2 — non-completed absolute count
        non_completed = m[m["bucket"].isin(["TERMINATED", "WITHDRAWN"])]
        n_non_completed = len(non_completed)

        # Part 3 — new failures (non-completed weak not already in gold)
        nc_ids = set(non_completed["nct_id"])
        new_fail_ids = nc_ids - gold_ids
        n_new_fail = len(new_fail_ids)
        n_nc_in_gold = len(nc_ids & gold_ids)

        # context: gold failures already available for this phase (gold ∩ weak, gold_y==0)
        gold_in_phase = set(weak["nct_id"]) & gold_ids
        n_gold_fail = sum(1 for nid in gold_in_phase if gold_y[nid] == 0)

        # context: new successes weak would also add (completed, not in gold)
        completed_ids = set(m[m["bucket"] == "COMPLETED"]["nct_id"])
        n_new_success = len(completed_ids - gold_ids)

        ratio = n_new_fail / n_gold_fail if n_gold_fail else float("inf")

        md.append("")
        md.append(f"- Non-completed (TERMINATED + WITHDRAWN): **{n_non_completed:,}**")
        md.append(f"- ...already in gold set: {n_nc_in_gold:,}")
        md.append(f"- ...**NEW failure examples (not in gold): {n_new_fail:,}**")
        md.append(f"- Gold failure examples already available (this phase): {n_gold_fail:,}")
        md.append(f"- New weak failures as multiple of gold failures: **{ratio:.1f}×**")
        md.append(
            f"- (For contrast: new COMPLETED weak trials that would also be added as "
            f"successes: {n_new_success:,} — these reintroduce the population shift.)"
        )
        md.append("")

        summary_rows.append(
            {
                "phase": p,
                "n_new_fail": n_new_fail,
                "n_gold_fail": n_gold_fail,
                "ratio": ratio,
                "n_new_success": n_new_success,
                "n_non_completed": n_non_completed,
            }
        )
        print(
            f"{PHASE_NAMES[p]:>10} | {n_non_completed:>9,} | {n_new_fail:>8,} | "
            f"{n_gold_fail:>9,} | {ratio:>7.1f}× | {n_new_success:>11,}"
        )

    # ── Recommendation ────────────────────────────────────────────────────────
    total_new_fail = sum(r["n_new_fail"] for r in summary_rows)
    total_gold_fail = sum(r["n_gold_fail"] for r in summary_rows)
    min_ratio = min(r["ratio"] for r in summary_rows)

    md.append("## Recommendation")
    md.append("")
    md.append(
        f"Across phases the weak set adds **{total_new_fail:,} new real failure examples** "
        f"vs **{total_gold_fail:,}** already in gold (min per-phase ratio {min_ratio:.1f}×)."
    )
    md.append("")
    if min_ratio >= 0.5 and total_new_fail >= 2000:
        rec = (
            "**There is substantial extra failure signal — weak+gold with covariate "
            "correction is worth trying as a challenger.** The non-completed weak trials add "
            "1.7–2.3× the gold failure pool per phase and are ~99% trustworthy. But note both "
            "naive mixes distort the class prior in opposite directions: dumping in all weak "
            "data swings it success-heavy (the population shift returns, ~90k extra "
            "successes); adding only weak failures swings it failure-heavy (e.g. Phase I "
            "goes from 19% to ~8% positive). The principled route is weak+gold with "
            "importance weighting toward the gold/deployment covariate distribution, class "
            "prior fixed to gold base rates (scale_pos_weight as already specified). Keep "
            "gold-only as the baseline and only promote the weak-augmented challenger if it "
            "beats it on the gold-eval PR-AUC gate."
        )
    else:
        rec = (
            "**Stick with gold-only.** The weak set is too completion-dominated to add a "
            "meaningful failure pool beyond gold; the added complexity of covariate "
            "correction is not justified."
        )
    md.append(rec)
    md.append("")

    OUT_MD.write_text("\n".join(md))
    print()
    print(f"Wrote {OUT_MD.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
